Support for MediaElement Js plugin for Video and Audio controls
DFE-Digital/childrens-social-care-cpd pull request #292
Opened 2023-10-03 14:04 UTC by nnagepat

2023-10-03 14:19 UTC, cairnsj requested changes
Need to unbundle CSS and only include scripts on pages that need it.

2023-10-03 14:19 UTC, cairnsj commented on Childrens-Social-Care-CPD/Views/Shared/_SiteLayout.cshtml
This includes them on every page in the site, we only really want these on the pages where the content is shown.

2023-10-03 14:19 UTC, cairnsj commented on Childrens-Social-Care-CPD/styles/scss/overrides/_mediaelement-player.scss
Again can we only link to this on pages that have the player instead of bundling it?

2023-10-04 12:19 UTC, nnagepat commented on Childrens-Social-Care-CPD/Views/Shared/_SiteLayout.cshtml
Resolved

2023-10-04 12:20 UTC, nnagepat commented on Childrens-Social-Care-CPD/styles/scss/overrides/_mediaelement-player.scss
Resolved

2023-10-04 12:52 UTC, cairnsj approved these changes

2023-10-04 13:11 UTC, merged

2023-10-04 13:12 UTC, rgparkins commented
:tada: This PR is included in version 1.21.0 :tada:

The release is available on [GitHub release](https://github.com/DFE-Digital/childrens-social-care-cpd/releases/tag/v1.21.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: