Feat: Moved Beta Banner
DFE-Digital/childrens-social-care-cpd pull request #328
Opened 2023-11-20 08:39 UTC by MartinBelton-gov

Moved Beta Banner to new location.

Margins are the same as: https://vcf-sw-career-dev-prototype.herokuapp.com/current/futurestate/resources

![image](https://github.com/DFE-Digital/childrens-social-care-cpd/assets/111495215/7ea9b0ce-e94d-4fbd-8531-cc751e75248d)

2023-11-20 09:41 UTC, cairnsj commented
The Error page template will also need updating as it displays the beta banner too.

2023-11-20 10:33 UTC, cairnsj requested changes

2023-11-20 10:45 UTC, MartinBelton-gov commented on Childrens-Social-Care-CPD/Views/Shared/_SiteLayout.cshtml
> +    <partial name="_BetaBanner" />
Moved the _BetaBanner inside the main tag (see screen shots)

2023-11-20 11:20 UTC, merged

2023-11-21 10:44 UTC, rgparkins commented
:tada: This PR is included in version 1.33.1 :tada:

The release is available on [GitHub release](https://github.com/DFE-Digital/childrens-social-care-cpd/releases/tag/v1.33.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: