Sfsw 2656 create proposal for new page rendering process for training modules
DFE-Digital/childrens-social-care-cpd pull request #568
Opened 2024-11-29 09:34 UTC by mattb-hippo

This is the documentation for the proposal for a new approach to rendering pages for Pathways training modules

2024-11-29 11:57 UTC, nealhippo requested changes
• Can we make sure update the document to be inline with Claire and Jonathan's comment (attached at end of comment).
• What are the options for TOC (mentioned on calls this week)
• Are there considerations front end matter matter inclusion exclusion etc... (optional)
• Are there considerations for things like content excluded from TOC

From ticket: https://dfedigital.atlassian.net/browse/SFSW-2538
@Maria Crawford Have spoken to Claire and Jonathan and we think it’s best to make the naming conventions generic (i.e. training module) so that they can potentially service a purpose for future bits of work.

2024-11-29 15:54 UTC, Maria-C1 commented
> From ticket: https://dfedigital.atlassian.net/browse/SFSW-2538 @maria Crawford Have spoken to Claire and Jonathan and we think it’s best to make the naming conventions generic (i.e. training module) so that they can potentially service a purpose for future bits of work.

See most recent update on that ticket: 
> On looking again at this, there are some 'pathways-specific' buttons in the designs currently in UR, which means that **we will need to go with the more specific naming**. For example, the 'Go back to all pathways' button on the declaration page.

2024-12-02 11:35 UTC, nealhippo approved these changes

2024-12-02 11:35 UTC, merged

2024-12-02 15:58 UTC, mattb-hippo commented
:tada: This PR is included in version 3.10.0-next.4 :tada:

The release is available on [GitHub release](https://github.com/DFE-Digital/childrens-social-care-cpd/releases/tag/v3.10.0-next.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: